apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: smart-ranking-api
  annotations:
    github.com/project-slug: luis-henrique-carvalho/smart-ranking-api
spec:
  type: other
  lifecycle: unknown
  owner: guests
