version: '3.8'

services:
  smart-ranking-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    container_name: "db"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
